import type { Metadata } from 'next'
import { Inter, Yeseva_One } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/toaster'
import readUserSession from '@/lib/actions'
import { cn } from '@/lib/utils'
import { Session } from '@supabase/supabase-js'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})
const yesevaOne = Yeseva_One({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-yesevaone',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: {
	children: React.ReactElement;
  params: {
    session: Session|null
  }
}) {
  const { data } = await readUserSession()
  params.session = data?.session

  return (
    <html lang="en">
      <body className={cn(inter.variable, yesevaOne.variable, 'font-sans')}>
        <div />
        {children}
        <Toaster />
      </body>
    </html>
  )
}
