import type { Metadata } from 'next'
import { Inter, Yeseva_One } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/toaster'
import Link from 'next/link'
import readUserSession from '@/lib/actions'
import { cn } from '@/lib/utils'
import Header from '@/components/ui/molecules/Header'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})
const yesevaOne = Yeseva_One({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-yesevaone',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
	children: React.ReactNode;
}) {
  const { data } = await readUserSession()

  return (
    <html lang="en">
      <body className={cn(inter.variable, yesevaOne.variable, 'font-sans')}>
        <div />
        <div className="flex flex-col justify-stretch min-h-screen">
          <Header session={data.session} />
          <div className="grow pt-4 pb-8 print:pt-0 print:pb-0">
            {children}
          </div>
          <div className="bg-primary p-4 text-white print:hidden">
            <div className="max-w-5xl m-auto grid grid-cols-12">
              <div className="col-span-8">
                <span className="text-3xl font-display text-white">Reciparse</span>
              </div>
              <div className="col-span-4 grid grid-cols-2">
                <div className="col-span-1 text-xs">
                  <h4 className="font-semibold text-xs mt-2 mb-4">Account</h4>
                  <ul className="space-y-2">
                    {!data.session ? (
                      <>
                        <li><Link href="/auth-server-action#signin">Sign In</Link></li>
                        <li><Link href="/auth-server-action#registeer">Register</Link></li>
                      </>
                    ) : (<>
                      <li>
                        <Link href="/account">My Profile</Link>
                      </li>
                      <li>
                        <Link href="/account/favorites">My Favorites</Link>
                      </li>
                    </>)}
                    <li><Link href="/info/bookmarklet">Bookmarklet</Link></li>
                  </ul>
                </div>
                <div className="col-span-1 text-xs">
                  <h4 className="font-semibold text-xs mt-2 mb-4">Other Links</h4>
                  <ul className="space-y-2">
                    <li>
                      <Link href="/info/support">Support the developer</Link>
                    </li>
                    <li>
                      <Link href="/info/privacy">Privacy policy</Link>
                    </li>
                    <li>
                      <Link href="/info/cookies">Cookie policy</Link>
                    </li>
                    <li>
                      <Link href="/info/terms">Terms of use</Link>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
        <Toaster />
      </body>
    </html>
  )
}
