import type { Metadata } from 'next'
import { Inter, Yeseva_One } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/toaster'
import Link from 'next/link'
import Image from 'next/image'
import { Button } from '@/components/ui/button'
import readUserSession from '@/lib/actions'
import SignOut from './auth-server-action/components/SignOut'
import { cn } from '@/lib/utils'
import { CaretDownIcon } from '@radix-ui/react-icons'
import MenuDropdown from '@/components/ui/molecules/MenuDropdown'
import ParseRecipeDialog from '@/components/ui/molecules/ParseRecipeDialog'

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})
const yesevaOne = Yeseva_One({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-yesevaone',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
	children: React.ReactNode;
}) {
  const { data } = await readUserSession()

  return (
    <html lang="en">
      <body className={cn(inter.variable, yesevaOne.variable, 'font-sans')}>
        <div />
        <div className="flex flex-col justify-stretch min-h-screen">
          <div className="print:hidden px-4 border-b border-b-slate-200 sticky top-0 bg-white z-10">
            {data.session && (
              <div className="bg-slate-50">
                <div className="max-w-5xl m-auto flex items-center justify-end gap-3 text-sm">
                  <Link href="/account" className="p-2">My Account</Link>
                  <SignOut />
                </div>
              </div>
            )}
            <div className="max-w-5xl m-auto flex items-center gap-3">
              <div className="flex items-center gap-6 grow">
                <Link href="/">
                  <span className="sr-only">Reciparse.com</span>
                  <Image width="100" height="100" className="h-8 max-w-[125px] w-auto" src="/logo.svg" alt="" />
                </Link>
                <div className="flex items-center">
                  {data.session && (
                    <>
                      <MenuDropdown
                        label={<button className="data-[state=open]:bg-slate-50 cursor-pointer inline-flex gap-1 items-center py-6 px-4 hover:bg-slate-50">My stuff <CaretDownIcon className="w-5 h-5" /></button>}
                        items={[
                          <Link key="recipes" href="/recipes" className="py-2 px-4 hover:bg-slate-50 block focus-visible:outline-0">Recipes</Link>,
                          <Link key="collections" href="/collections" className="py-2 px-4 hover:bg-slate-50 block focus-visible:outline-0">Collections</Link>,
                        ]}
                      />
                      <Link href="/recipes/add" className="py-6 px-4 border-b border-b-transparent hover:bg-slate-50 hover:border-b-primary -mb-[1px]">Add a recipe</Link>
                    </>
                  )}
                  <ParseRecipeDialog trigger={<button className="py-6 px-4 border-b border-b-transparent hover:bg-slate-50 hover:border-b-primary -mb-[1px]">Parse a recipe</button>} />
                </div>
              </div>
              <div className="flex items-center gap-3">
                {data?.session ? null : <><Link href="/auth-server-action"><Button variant="outline">Sign In</Button></Link><Button>Sign Up</Button></>}
              </div>
            </div>
          </div>
          <div className="grow pt-4 pb-8 print:pt-0 print:pb-0">
            {children}
          </div>
          <div className="bg-primary p-4 text-white print:hidden">
            <div className="max-w-5xl m-auto grid grid-cols-12">
              <div className="col-span-8">
                <span className="text-3xl font-display text-white">Reciparse</span>
              </div>
              <div className="col-span-4 grid grid-cols-2">
                <div className="col-span-1 text-xs">
                  <h4 className="font-semibold text-xs mt-2 mb-4">Account</h4>
                  <ul className="space-y-2">
                    {!data.session ? (
                      <>
                        <li><Link href="/auth-server-action#signin">Sign In</Link></li>
                        <li><Link href="/auth-server-action#registeer">Register</Link></li>
                      </>
                    ) : (<>
                      <li>
                        <Link href="/account">My Profile</Link>
                      </li>
                      <li>
                        <Link href="/account/favorites">My Favorites</Link>
                      </li>
                    </>)}
                    <li><Link href="/info/bookmarklet">Bookmarklet</Link></li>
                  </ul>
                </div>
                <div className="col-span-1 text-xs">
                  <h4 className="font-semibold text-xs mt-2 mb-4">Other Links</h4>
                  <ul className="space-y-2">
                    <li>
                      <Link href="/info/support">Support the developer</Link>
                    </li>
                    <li>
                      <Link href="/info/privacy">Privacy policy</Link>
                    </li>
                    <li>
                      <Link href="/info/cookies">Cookie policy</Link>
                    </li>
                    <li>
                      <Link href="/info/terms">Terms of use</Link>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
        <Toaster />
      </body>
    </html>
  )
}
