
import { Open_Sans, Yeseva_One } from 'next/font/google'
import classNames from 'classnames'

import { AuthContextProvider } from '@/context/AuthContext'

import './globals.css'

const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-opensans',
})
const yesevaOne = Yeseva_One({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-yesevaone',
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={classNames(openSans.className, openSans.variable, yesevaOne.variable)}>
      <body>
        <AuthContextProvider>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  )
}
