
import { Open_Sans, Yeseva_One } from 'next/font/google';
import classNames from 'classnames';
import { cookies } from 'next/headers';

import { AuthContextProvider } from '@/context/AuthContext';

import './globals.css';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { Database } from '@/types/database.types';

const openSans = Open_Sans({
  subsets: ['latin'],
  variable: '--font-opensans',
});
const yesevaOne = Yeseva_One({
  weight: '400',
  subsets: ['latin'],
  variable: '--font-yesevaone',
});


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const dynamic = 'force-dynamic';

export default async function RootLayout({ children }: {
  children: React.ReactNode
}) {
  const supabase = createServerComponentClient<Database>({ cookies });

  const { data: { session } } = await supabase.auth.getSession();
  return (
    <html lang="en" className={classNames(openSans.className, openSans.variable, yesevaOne.variable)}>
      <body>
        <AuthContextProvider user={session?.user || null}>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
